### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by bayanistnahtc** [rshin/seq2struct#29]
I followed the instructions in README file. All steps were okay before the evaluation one. Running the command: "python eval.py --config configs/spider-20190205/arxiv-1906.11790v1.jsonnet --inferred <PATH FOR INFERENCE OUTPUT> --output <PATH FOR EVAL OUTPUT> --section val"
performs an error:

Traceback (most recent call last):
  File "eval.py", line 37, in <module>
    main()
  File "eval.py", line 22, in main
    evaluate_beams_individually=args.evaluate_beams_individually)
  File "/home/user/Documents/synthesis/seq2struct/seq2struct/utils/evaluation.py", line 32, in compute_metrics
    return logdir, evaluate_default(data, inferred_lines)
  File "/home/user/Documents/synthesis/seq2struct/seq2struct/utils/evaluation.py", line 44, in evaluate_default
    metrics = data.Metrics(data)
  File "/home/user/Documents/synthesis/seq2struct/seq2struct/datasets/spider.py", line 151, in __init__
    'match')
  File "/home/user/Documents/synthesis/seq2struct/third_party/spider/evaluation.py", line 372, in __init__
    self.schemas[db_name] = Schema(get_schema(db_path))
  File "/home/user/Documents/synthesis/seq2struct/third_party/spider/process_sql.py", line 88, in get_schema
    conn = sqlite3.connect(db)
sqlite3.OperationalError: unable to open database file

Could you help, please?

**Comment by bayanistnahtc** [comment]
Okay, I have found the answer. To deal with this problem you just need to add all spider "database" folder to the path "seq2struct/data". This is not obvious at the first time.
